# SPDX-License-Identifier: GPL-2.0
#
# Makefile for linux/drivers/platform
#

obj-$(CONFIG_ESP32S31_DT_OVERLAY) += esp32s31-overlay.o
obj-$(CONFIG_ESP32S31_RADIO_SMODE_DRIVER) += esp32s31-radio-smode.o
obj-$(CONFIG_ESP32S31_RADIO_BLOBS) += esp32s31-radio-idf.o

obj-$(CONFIG_X86)		+= x86/
obj-$(CONFIG_LOONGARCH)		+= loongarch/
obj-$(CONFIG_MELLANOX_PLATFORM)	+= mellanox/
obj-$(CONFIG_MIPS)		+= mips/
obj-$(CONFIG_OLPC_EC)		+= olpc/
obj-$(CONFIG_GOLDFISH)		+= goldfish/
obj-$(CONFIG_CHROME_PLATFORMS)	+= chrome/
obj-$(CONFIG_CZNIC_PLATFORMS)	+= cznic/
obj-$(CONFIG_SURFACE_PLATFORMS)	+= surface/
obj-$(CONFIG_ARM64_PLATFORM_DEVICES)	+= arm64/
