/* SPDX-License-Identifier: GPL-2.0 */

#ifndef _ASM_RISCV_SPARSEMEM_H
#define _ASM_RISCV_SPARSEMEM_H

#ifdef CONFIG_SPARSEMEM
#ifdef CONFIG_64BIT
#define MAX_PHYSMEM_BITS	56
#define SECTION_SIZE_BITS	27
#else
#define MAX_PHYSMEM_BITS	32
#define SECTION_SIZE_BITS	CONFIG_RISCV_SPARSEMEM_SECTION_SIZE_BITS
#endif /* CONFIG_64BIT */
#endif /* CONFIG_SPARSEMEM */

#endif /* _ASM_RISCV_SPARSEMEM_H */
